### ISSUE TITLE
Eloquent self::update([...]) is updating attributes not given as parameter

### ISSUE THREAD

**Issue by jrean** [michaeldyrynda/laravel-nullable-fields#19] opened 2017-01-12 07:00 UTC
https://github.com/laravel/framework/issues/17285

I finally noticed the issue is only appearing when using your package.

Am I missing something?

Is this a bug?

Can you please give me some feedback?

Based on Slack (larachat) discussion. It seems you are:

https://github.com/michaeldyrynda/laravel-nullable-fields/blob/master/src/NullableFields.php#L171

```
they are only checking if the model has a set mutator (which yours doesnt)

[3:03]  
they should probably just pull the attribute with `$this->attributes['foo']` which would bypass the mutators completely
```

**Comment by michaeldyrynda** [comment] 2017-01-12 21:51
Thanks for reporting this @jrean.

From the example in the framework issue, what is `baz` being set to? Is it just `null`? And the expectation is that `baz` is not updated at all, correct?

Just clarifying to so I can start with a failing test to fix it up.

**Comment by michaeldyrynda** [comment] 2017-01-12 22:19
@jrean - I've started work on this. Can you take a look at the code in c546497 and let me know if this is the case you're working with? 

Looks like that test passes based on the information from laravel/framework#17285. Query executed per below screenshot. It doesn't appear to be touching the `baz` attribute at all. Even if I add `baz` to the `$nullable` property, it doesn't get updated in the query.

I was able to get SQLite to throw an error *if* I didn't declare the field nullable *and* didn't try and set a value for it, but that was on insert, not update. This is because creating the record (in SQLite) will default to setting a value to `null`, even if the field is not defined as such. To get around this, best to set `->default('')` on your migration in that instance.

```
NullableFieldsIntegrationTest::it_does_not_update_fields_when_they_are_not_explicitly_specified
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: foo.baz (SQL: insert into "foo" ("foo", "bar") values (0, 0))
```

You'll note, though, this is not the package (`baz` is not part of the query), but SQLite defaulting the `baz` field to `null`.

This is the create statement Laravel generates for the schema for `foo`:

`"create table "foo" ("id" integer not null primary key autoincrement, "foo" tinyint(1) null default '0', "bar" tinyint(1) null default '0', "baz" varchar not null)"`

![screen shot 2017-01-13 at 9 26 10 am](https://cloud.githubusercontent.com/assets/558441/21911810/5dad390a-d972-11e6-8137-1124c48b0bac.png)

Let me know if I've missed anything so I can refine the test before tackling a fix as needed.

![image](https://cloud.githubusercontent.com/assets/558441/21910478/1c3833d6-d96c-11e6-9c29-903c5057c553.png)

**Comment by jrean** [comment] 2017-01-16 06:04
Hi @michaeldyrynda 

Following the exemple:

```
class Foo extends Model
{
    protected $fillable = [
        'foo',
        'bar',
        'baz',
    ];

    /**
     * The attributes that are nullable.
     *
     * @var array
     */
    protected $nullable = [
        'foo',
        'bar',
        'baz',

    protected function doSomething()
    {
        $this->update([
            'foo' => true,
            'bar' => true,
            // note baz is not set to be updated
        ]);
    }

    public function getBazAttribute($value)
    {
        return 'XXX';
    }

...
```

Somewhere in a Controller, calling the `$model->doSomething()` should only update `foo` & `bar`.
For a reason I can't explain, while (and only while) using your package ; if I have an accessor for `baz` like in the code sample ; when calling `$model->doSomething()`, `foo`, `bar` AND `baz` will be updated. `baz` will be updated with the return value of the accessor.

Hope it is more clear :-)

**Comment by michaeldyrynda** [comment] 2017-01-16 06:35
Hey @jrean, unfortunately, based on this information I'm still not able to come up with a failing test case. If you were able to submit one, I can dig further.

Have a look in the branch mentioned above at what I've got so far if; you may able to tweak it a bit to get it to fail as you've suggested.

**Comment by jrean** [comment] 2017-01-16 06:39
Hey @michaeldyrynda thanks.
I'm worried to properly understand your lines.

You mean when you reproduce my code and you use the `doSomething()` method, even if you have an accessor declared for `baz` it won't update `baz` in the DB during the update?

**Comment by michaeldyrynda** [comment] 2017-01-16 06:45
Yeah, that's what I'm getting at.

You can see in the test case, I've got the class as you've described above and calling `doSomething` behaves itself.

**Comment by jrean** [comment] 2017-01-16 06:50
So weird.
I will go into it then but I have no time for the next few days.
If you want to close the ticket, I will still comment into it.
Thxs

**Comment by michaeldyrynda** [comment] 2017-01-16 09:36
All good, let me know what you find. I'll leave the issue open for now, until we're sure we can't reproduce it (and in case anybody else stumbles upon it).

**Comment by michaeldyrynda** [comment] 2017-03-08 11:41
Closing this for now as it's been nearly two months without update. Feel free to comment again / reopen if you come up with a failing unit test, though!

**Closed as completed by michaeldyrynda** 2017-03-08 11:41 UTC
Labels: more info
